### ISSUE TITLE
beta theme buttons

### ISSUE THREAD

**Issue by heroesiiifan** [vcmi-mods/h3-themes#8]
@Aph-ra Do you have psd or xcf files for beta theme buttons? To translate them.

**Comment by Aph-ra** [comment]
I do, but I'll have to leave instructions alongside it if people want to make their own version of this, since I work in my own weird way & GIMP doesn't allow for editing already edited text. If you'd like that, I can upload that within the week.

Alternatively, let me know what translations are wanted with the words for each button and I'll make them all myself! Might be easier that way!

**Comment by heroesiiifan** [comment]
Thanks!

German:
```
NEW GAME:   NEUES SPIEL
LOAD GAME:   SPIEL LADEN
HIGH SCORE:   HIGHSCORE
CREDITS:   CREDITS
QUIT:   BEENDEN

SINGLE SCENARIO:   EINZEL-SZENARIO
MULTI-PLAYER:   MULTI-PLAYER
CAMPAIGN:   KAMPAGNE
TUTORIAL:   ÜBUNGS-SPIEL
BACK:   ZURÜCK

SHADOW OF DEATH:   SHADOW OF DEATH
RESTORATION OF ERATHIA:   RESTORATION OF ERATHIA
ARMAGEDDONS BLADE:   ARMAGEDDONS BLADE
CUSTOM:   EIGENE
BACK:   ZURÜCK

NEW GAME:   NEUES SPIEL
LOAD GAME:   SPIEL LADEN
```

Pay attention to the umlauts.

**Comment by Aph-ra** [comment]
Not sure how to add translation compatibility so here are the files for the German translation that can be added:
[Beta GERMAN.zip](https://github.com/user-attachments/files/17970308/Beta.GERMAN.zip)

The config file is needed to center the translated "New Game" and "Load Game" images that appear in the middle of the screen, but otherwise no other files besides the new buttons and those two images need to be duplicated (if that's how it works).

**Comment by heroesiiifan** [comment]
Thanks!

Added it as compatibility mod in german translation: https://github.com/vcmi-mods/german-translation/tree/vcmi-1.6/mods/german-translation-theme-beta

Everyone uses this mod and german mod will have it in german. :)
